config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#show'

  devise_for :users
  # resources :users, only: [:show]
  resources :apps
  resources :run_apps, only: [:index, :show]
  resource :clone_app, only: [:index, :show]
  resource :code, only: [:show, :update]
  resource :publish, only: [:show, :update]
  resource :exercise_apps, only: [:destroy]

  resource :docs, only: [:show]
  resources :chapters
  resources :pages
  resource :move_page, only: [:show]
  resources :sections

  resources :games, only: [:index, :show, :new, :update, :destroy]

  resource :yahtzee, module: :yahtzee do
    resource :game, only: [:show]
    resource :roll, only: [:create]
    resource :complete_turn, only: [:create]
  end

  resource :server, only: [:show]
  resource :fake_post, only: [:create]

  resource :client, only: [:show]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/controllers/docs_controller.rb
class DocsController < ApplicationController

  def show
    @chapters = Chapter.all
  end

  # def new
  #   @app = current_user.apps.build
  # end
  #
  # def create
  #   @app = current_user.apps.build strong_params
  #   if @app.save
  #     redirect_to @app
  #   else
  #     render :new
  #   end
  # end
  #
  # def edit
  #   @app = current_user.apps.find(params[:id])
  # end
  #
  # def update
  #   @app = current_user.apps.find(params[:id])
  #   @app.update(strong_params)
  #   redirect_to code_path(app_id: @app.id)
  # end
  #
  # def destroy
  #   @app = current_user.apps.find(params[:id])
  #   @app.destroy
  #   redirect_to apps_path
  # end
  #
  # private
  #
  # def strong_params
  #   params.require(:app).permit(:label, :published)
  # end

end

app/views/docs/show.html.erb
<br>
<div>
  <%= link_to icon_text('fa-plus', "New chapter"), new_chapter_path, class: 'btn btn-link' if current_user.is_admin? %>
</div>
<br>
<% @chapters.each do |c| %>
  <h3>
    <%= c.order %>. <%= c.name %>
    <%= content_tag :div, class: 'btn-group pull-right' do %>
      <%= content_tag :div, class: 'btn-group' do %>
        <%= link_to icon_text('fa-plus', "New page"), new_page_path(chapter_id: c.id), class: 'btn btn-link' %>
      <% end %>
      <%= content_tag :div, class: 'btn-group' do %>
        <%= link_to edit_chapter_path(c), class: 'btn btn-link' do %>
          <%= icon('fa-edit') %>
        <% end %>
      <% end %>
      <%= content_tag :div, class: 'btn-group' do %>
        <%= button_to chapter_path(c), method: :delete, class: 'btn btn-link', 'data-confirm': 'Are you sure that you want to delete this chapter?' do %>
          <%= icon('fa-trash-o') %>
        <% end %>
      <% end %>
    <% end if current_user.is_admin? %>
  </h3>

  <%= markdown_text c.preface %>

  <% c.pages.each do |p| %>
    <p>
    <%= content_tag :div, class: 'btn-group' do %>
      <%= link_to ( "#{p.order}. #{p.name}" ), page_path(p), class: 'btn btn-lg btn-link' %>
    <% end %>
    <%= content_tag :div, class: 'btn-group pull-right' do %>
      <%= content_tag :div, class: 'btn-group' do %>
        <%= link_to icon('fa-caret-up'), move_page_path(page_id: p.id) %>
        <%= link_to edit_page_path(p), class: 'btn btn-link' do %>
          <%= icon('fa-edit') %>
        <% end %>
      <% end if current_user.is_admin? %>
      <%= content_tag :div, class: 'btn-group' do %>
        <%= button_to page_path(p), method: :delete, class: 'btn btn-link', 'data-confirm': 'Are you sure that you want to delete this page?' do %>
          <%= icon('fa-trash-o') %>
        <% end if current_user.is_admin? %>
      <% end %>
    <% end %>
    <div class='page_preface'>
      <%= markdown_text p.preface %>
    </div>
  </p>

  <% end %>


<% end %>