config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#show'

  devise_for :users
  # resources :users, only: [:show]
  resources :apps
  resources :run_apps, only: [:index, :show]
  resource :clone_app, only: [:index, :show]
  resource :code, only: [:show, :update]
  resource :publish, only: [:show, :update]
  resource :exercise_apps, only: [:destroy]

  resource :docs, only: [:show]
  resources :chapters
  resources :pages
  resource :move_page, only: [:show]
  resources :sections

  resources :games, only: [:index, :show, :new, :update, :destroy]

  resource :yahtzee, module: :yahtzee do
    resource :game, only: [:show]
    resource :roll, only: [:create]
    resource :complete_turn, only: [:create]
  end

  resource :server, only: [:show]
  resource :fake_post, only: [:create]

  resource :client, only: [:show]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/controllers/codes_controller.rb
class CodesController < ApplicationController

  def show
    @app = current_user.apps.find(params[:app_id])
  end

  def update
    @app = current_user.apps.find(params[:app_id])
    @app.update(strong_params)
  end

  private

  def strong_params
    params.require(:app).permit(:file)
  end

end

app/views/codes/show.html.erb
<%= link_to :app, run_app_path(@app), target: :yahtzee_client, id: 'run_app_link', style: 'display: none;' %>
<%= content_tag :div, class: 'btn-group' do %>
  <%= link_to icon('fa-arrow-up'), apps_path, class: 'btn btn-lg btn-link' %>
<% end %>
<%= form_for @app, url: code_path(app_id: @app.id), remote: true do |f| %>
  <%= content_tag :h3 do %>
    <%= @app.label %>
    <%= content_tag :div, class: 'btn-group pull-right' do %>
      <%= button_tag type: :submit, class: 'btn btn-lg btn-link' do %>
        <%= content_tag(:i, nil, class: 'fa fa-save') %> Save
      <% end %>
    <% end %>
  <% end %>
  <%= content_tag :p do %>
    <%= f.text_area :file, class: 'app_input', spellcheck: false %>
  <% end %>
<% end %>

<p>
Yahtzee Server<br>
API: <%= Rails.application.config.app_host_path %>/yahtzee/<br>
Token for <%= current_user.username %>: <%= current_user.api_token %><br>
</p>

app/views/codes/update.js.erb
$('#run_app_link')[0].click();