config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#show'

  devise_for :users
  # resources :users, only: [:show]
  resources :apps
  resources :run_apps, only: [:index, :show]
  resource :clone_app, only: [:index, :show]
  resource :code, only: [:show, :update]
  resource :publish, only: [:show, :update]
  resource :exercise_apps, only: [:destroy]

  resource :docs, only: [:show]
  resources :chapters
  resources :pages
  resource :move_page, only: [:show]
  resources :sections

  resources :games, only: [:index, :show, :new, :update, :destroy]

  resource :yahtzee, module: :yahtzee do
    resource :game, only: [:show]
    resource :roll, only: [:create]
    resource :complete_turn, only: [:create]
  end

  resource :server, only: [:show]
  resource :fake_post, only: [:create]

  resource :client, only: [:show]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/views/apps/_app.html.erb
<%= content_tag :div, class: 'btn-group' do %>
  <%= link_to ( app.label || 'No label!' ), code_path(app_id: app.id), class: 'btn btn-link' %>


  <div class="btn-group">
    <button type="button" class="btn btn-link dropdown-toggle" data-toggle="dropdown">
      <%= icon('fa-bars') %>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to icon_text('fa-edit', 'Edit'), edit_app_path(id: app.id) %></li>
      <li><%= link_to icon_text('fa-share-alt', 'Fork'), clone_app_path(id: app.id), 'data-confirm': 'Are you sure that you want to fork this app?' %></li>
      <li role="separator" class="divider"></li>
      <li>
        <%= button_to app_path(app), method: :delete, class: 'dropdown-item',
         'data-confirm': 'Are you sure that you want to delete this app?' do %>
          <%= icon_text('fa-trash-o', 'Delete') %>
        <% end %>
      </li>
    </ul>
  </div>

<% end %>

app/views/apps/edit.html.erb
<br>
<%= form_for @app do |f| %>
  <%= content_tag :div, class: "form-group" do %>
    <%= f.text_field :label, class: 'form-control' %>
  <% end %>
  <%= content_tag :div, class: "checkbox" do %>
    <%= f.label :published do %>
      <%= f.check_box :published %> Publish
    <% end %>
  <% end %>
  <%= content_tag :div, class: "checkbox" do %>
    <%= f.label :exercise do %>
      <%= f.check_box :exercise %> Exercise
    <% end %>
  <% end %>
  <%= content_tag :div, class: 'btn-group pull-left' do %>
    <%= button_tag type: :submit, class: 'btn btn-primary' do %>
      <%= content_tag(:i, nil, class: 'fa fa-edit') %> Update
    <% end %>
  <% end %>
<% end %>

app/views/apps/index.html.erb
<br>
<p><%= link_to icon_text('fa-plus', 'New'), new_app_path, class: 'btn btn-link' %></p>
<% @apps.reject(&:published).reject(&:exercise).each do |app| %>
  <%= render app %>
  <br>
<% end %>
<% @published_apps = @apps.select(&:published).reject(&:exercise) %>
<%= content_tag(:h5, 'Published') if @published_apps.any? %>
<% @published_apps.each do |app| %>
  <%= render app %>
  <br>
<% end %>
<% @exercise_apps = @apps.reject(&:published).select(&:exercise) %>
<%= content_tag(:h5) do %>
  <%= 'Exercises' %>
  <%= content_tag :div, class: "btn-group pull-right" do %>
    <%= button_to exercise_apps_path, method: :delete, class: 'btn btn-link', 'data-confirm': 'Are you sure that you want to delete all unpublished exercise apps?' do %>
      <%= icon_text('fa-trash-o', 'Delete all exercises') %>
    <% end unless current_user.is_admin? %>
  <% end %>
<% end if @exercise_apps.any? %>
<% @exercise_apps.each do |app| %>
  <%= render app %>
  <br>
<% end %>
<% @published_exercise_apps = @apps.select(&:published).select(&:exercise) %>
<%= content_tag(:h5, 'Published exercises') if @published_exercise_apps.any? %>
<% @published_exercise_apps.each do |app| %>
  <%= render app %>
  <br>
<% end %>

app/views/apps/new.html.erb
<br>
<%= form_for @app do |f| %>
  <%= content_tag :p do %>
    <%= f.text_field :label, class: 'form-control', placeholder: 'Give the app a label...' %>
  <% end %>
  <%= content_tag :p, class: 'btn-group pull-left' do %>
    <%= button_tag type: :submit, class: 'btn btn-primary' do %>
      <%= content_tag(:i, nil, class: 'fa fa-plus') %> Create
    <% end %>
  <% end %>

<% end %>